### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wiseaidev** [wiseaidev/rping#4]
- [x] Controllable net interface.
- [x] Fix TCP checksum
- [x] Fix TCP flags, and allow users to flood any tcp flag from CLI.
- [x] Randomize source IP address (~~limitation in `socket2`?~~).

![image](https://github.com/wiseaidev/rping/assets/62179149/f305f075-de4c-45be-b468-d820d8e90518)
